import fs from 'fs';
import path from 'path';
import { ServerModel } from '../models/serverModel';
import { ProcessManager } from './processManager';
import { MinecraftJarService } from './minecraftJarService';

export class InstallationWorker {
  private static queue: string[] = [];
  private static isProcessing = false;

  static enqueue(serverUuid: string): void {
    if (!this.queue.includes(serverUuid)) {
      this.queue.push(serverUuid);
    }
    this.processQueue();
  }

  static async processQueue(): Promise<void> {
    if (this.isProcessing || this.queue.length === 0) return;

    this.isProcessing = true;
    const serverUuid = this.queue.shift()!;

    try {
      await this.runInstallation(serverUuid);
    } catch (err: any) {
      console.error(`❌ Installation error for server ${serverUuid}:`, err);
    } finally {
      this.isProcessing = false;
      if (this.queue.length > 0) {
        this.processQueue();
      }
    }
  }

  private static getTimeStamp(): string {
    const d = new Date();
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${pad(d.getHours())}:${pad(d.getMinutes())}:${pad(d.getSeconds())}`;
  }

  private static log(serverUuid: string, category: string, message: string): void {
    const time = this.getTimeStamp();
    const line = `[${time}] [${category}] ${message}`;
    ProcessManager.getInstance().logOutput(serverUuid, line);
  }

  static async runInstallation(serverUuid: string): Promise<void> {
    const server = ServerModel.findByUuid(serverUuid);
    if (!server) return;

    const processMgr = ProcessManager.getInstance();

    // 1. Update status to 'installing'
    ServerModel.updateStatus(server.id, 'installing');
    this.log(serverUuid, 'Installer', `Creating server directory structure for "${server.name}"...`);

    const targetDir = server.directory || path.join(process.cwd(), 'storage', 'servers', serverUuid);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    // 2. Generate server.json metadata manifest
    this.log(serverUuid, 'Installer', 'Generating server.json manifest...');
    const serverJson = {
      uuid: server.uuid,
      name: server.name,
      software: server.software,
      version: server.version,
      java_version: server.java_version,
      port: server.port,
      ram_limit: server.ram_limit,
      cpu_limit: server.cpu_limit,
      disk_limit: server.disk_limit,
      created_at: server.created_at
    };
    fs.writeFileSync(path.join(targetDir, 'server.json'), JSON.stringify(serverJson, null, 2));

    // 3. Generate eula.txt
    this.log(serverUuid, 'Installer', 'Generating eula.txt (eula=true)...');
    fs.writeFileSync(path.join(targetDir, 'eula.txt'), '# Auto-generated by KineticGP Panel\neula=true\n');

    // 4. Generate server.properties
    this.log(serverUuid, 'Installer', `Generating server.properties (Allocated Port: ${server.port})...`);
    const propsPath = path.join(targetDir, 'server.properties');
    if (!fs.existsSync(propsPath)) {
      const defaultProps = `
# KineticGP Server Properties
server-port=${server.port}
query.port=${server.port}
motd=\\u00A7b${server.name} \\u00A77- Powered by \\u00A7bKineticGP
enable-rcon=false
max-players=20
online-mode=true
allow-nether=true
enable-command-block=true
gamemode=survival
difficulty=easy
pvp=true
view-distance=10
spawn-protection=0
`;
      fs.writeFileSync(propsPath, defaultProps.trim());
    }

    // 5. Create runtime folders
    const subDirs = ['logs', 'world', 'cache', 'plugins', 'mods', 'libraries'];
    for (const sd of subDirs) {
      const p = path.join(targetDir, sd);
      if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
    }

    // 6. Download Server JAR with live byte/speed logs
    ServerModel.updateStatus(server.id, 'downloading');
    this.log(serverUuid, 'Installer', `Fetching ${server.software} ${server.version} metadata...`);

    try {
      const downloadUrl = await MinecraftJarService.resolveDownloadUrl(server.software, server.version, (msg) => {
        this.log(serverUuid, 'HTTP', msg.replace('[HTTP] ', ''));
      });

      this.log(serverUuid, 'Installer', `Downloading server.jar from ${downloadUrl}...`);

      const jarPath = path.join(targetDir, 'server.jar');
      let lastPercent = -1;

      await MinecraftJarService.downloadFile(downloadUrl, jarPath, (downloaded, total, percent, speed) => {
        const downloadedFmt = MinecraftJarService.formatBytes(downloaded);
        const totalFmt = total > 0 ? MinecraftJarService.formatBytes(total) : 'Unknown';

        // Emit progress every 10% change or at finish
        if (percent % 10 === 0 && percent !== lastPercent) {
          lastPercent = percent;
          this.log(serverUuid, 'Download', `Receiving server.jar (${downloadedFmt} / ${totalFmt} - ${percent}% @ ${speed})`);
        }

        // Emit SSE progress event for UI progress bar
        processMgr.emit(`progress:${serverUuid}`, {
          step: 'downloading',
          percent,
          downloaded: downloadedFmt,
          total: totalFmt,
          speed
        });
      });

      const stat = fs.statSync(jarPath);
      const sizeMb = (stat.size / (1024 * 1024)).toFixed(1);
      this.log(serverUuid, 'Download', `Completed (${sizeMb} MB).`);

      // 7. Finalize installation & transition to 'offline' (Ready to start)
      ServerModel.updateStatus(server.id, 'offline');
      this.log(serverUuid, 'Installer', 'Installation completed successfully.');
      this.log(serverUuid, 'Installer', 'Server is ready. Press "Start" to launch Java process.');

      processMgr.emit(`progress:${serverUuid}`, {
        step: 'ready',
        percent: 100
      });

    } catch (err: any) {
      ServerModel.updateStatus(server.id, 'failed');
      this.log(serverUuid, 'ERROR', `Installation failed: ${err.message}`);
      this.log(serverUuid, 'Installer', 'You may click "Retry Installation" to try downloading again.');
    }
  }

  static retry(serverUuid: string): void {
    this.enqueue(serverUuid);
  }
}
