import fs from 'fs';
import path from 'path';
import { ServerModel } from '../models/serverModel';
import { ProcessManager } from './processManager';
import { MinecraftJarService } from './minecraftJarService';

export class InstallationWorker {
  private static queue: string[] = [];
  private static isProcessing = false;

  static enqueue(serverUuid: string): void {
    if (!this.queue.includes(serverUuid)) {
      this.queue.push(serverUuid);
    }
    this.processQueue();
  }

  static async processQueue(): Promise<void> {
    if (this.isProcessing || this.queue.length === 0) return;

    this.isProcessing = true;
    const serverUuid = this.queue.shift()!;

    try {
      await this.runInstallation(serverUuid);
    } catch (err: any) {
      console.error(`❌ Installation error for server ${serverUuid}:`, err);
    } finally {
      this.isProcessing = false;
      if (this.queue.length > 0) {
        this.processQueue();
      }
    }
  }

  static async runInstallation(serverUuid: string): Promise<void> {
    const server = ServerModel.findByUuid(serverUuid);
    if (!server) return;

    const processMgr = ProcessManager.getInstance();

    // 1. Update status to 'installing'
    ServerModel.updateStatus(server.id, 'installing');
    processMgr.logOutput(serverUuid, '[KineticGP] 🚀 Provisioning server instance...');
    processMgr.logOutput(serverUuid, `[KineticGP] Server Name: ${server.name}`);
    processMgr.logOutput(serverUuid, `[KineticGP] Engine: ${server.software} ${server.version}`);
    processMgr.logOutput(serverUuid, `[KineticGP] Java Runtime: Java ${server.java_version}`);
    processMgr.logOutput(serverUuid, `[KineticGP] Memory Quota: ${server.ram_limit} MB`);

    const targetDir = server.directory || path.join(process.cwd(), 'storage', 'servers', serverUuid);
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }

    // 2. Generate server.json metadata manifest
    processMgr.logOutput(serverUuid, '[KineticGP] Creating server.json manifest & configuration...');
    const serverJson = {
      uuid: server.uuid,
      name: server.name,
      software: server.software,
      version: server.version,
      java_version: server.java_version,
      port: server.port,
      ram_limit: server.ram_limit,
      cpu_limit: server.cpu_limit,
      disk_limit: server.disk_limit,
      created_at: server.created_at
    };
    fs.writeFileSync(path.join(targetDir, 'server.json'), JSON.stringify(serverJson, null, 2));

    // 3. Generate eula.txt
    processMgr.logOutput(serverUuid, '[KineticGP] Accepting Mojang EULA (eula.txt)...');
    fs.writeFileSync(path.join(targetDir, 'eula.txt'), '# Auto-generated by KineticGP Panel\neula=true\n');

    // 4. Generate server.properties
    processMgr.logOutput(serverUuid, `[KineticGP] Generating server.properties (Port: ${server.port})...`);
    const propsPath = path.join(targetDir, 'server.properties');
    if (!fs.existsSync(propsPath)) {
      const defaultProps = `
# KineticGP Server Properties
server-port=${server.port}
query.port=${server.port}
motd=\\u00A7b${server.name} \\u00A77- Powered by \\u00A7bKineticGP
enable-rcon=false
max-players=20
online-mode=true
allow-nether=true
enable-command-block=true
gamemode=survival
difficulty=easy
pvp=true
view-distance=10
spawn-protection=0
`;
      fs.writeFileSync(propsPath, defaultProps.trim());
    }

    // 5. Create runtime folders
    const subDirs = ['logs', 'world', 'cache', 'plugins', 'mods', 'libraries'];
    for (const sd of subDirs) {
      const p = path.join(targetDir, sd);
      if (!fs.existsSync(p)) fs.mkdirSync(p, { recursive: true });
    }

    // 6. Download Server JAR with live progress percentages
    ServerModel.updateStatus(server.id, 'downloading');
    processMgr.logOutput(serverUuid, `[KineticGP] Resolving download URL for ${server.software} ${server.version}...`);

    try {
      const downloadUrl = await MinecraftJarService.resolveDownloadUrl(server.software, server.version);
      processMgr.logOutput(serverUuid, `[KineticGP] Downloading server.jar from ${downloadUrl}...`);

      let lastEmittedPercent = -1;
      const jarPath = path.join(targetDir, 'server.jar');

      await MinecraftJarService.downloadFile(downloadUrl, jarPath, (percent) => {
        if (percent % 15 === 0 && percent !== lastEmittedPercent) {
          lastEmittedPercent = percent;
          processMgr.logOutput(serverUuid, `[KineticGP Download] Progress: ${percent}%`);
        }
      });

      const stat = fs.statSync(jarPath);
      const sizeMb = (stat.size / (1024 * 1024)).toFixed(1);
      processMgr.logOutput(serverUuid, `[KineticGP] Download complete (${sizeMb} MB).`);

      // 7. Update status to 'offline' (Ready to start)
      ServerModel.updateStatus(server.id, 'offline');
      processMgr.logOutput(serverUuid, '[KineticGP] ✅ Installation finished successfully.');
      processMgr.logOutput(serverUuid, '[KineticGP] Server is ready to start.');

    } catch (err: any) {
      ServerModel.updateStatus(server.id, 'failed');
      processMgr.logOutput(serverUuid, `[KineticGP Error] ❌ Installation failed: ${err.message}`);
      processMgr.logOutput(serverUuid, '[KineticGP Error] You may click "Retry Installation" to try downloading again.');
    }
  }

  static retry(serverUuid: string): void {
    this.enqueue(serverUuid);
  }
}
